### ISSUE TITLE
facet search

### ISSUE THREAD

**Issue by ohnorobo** [codeforboston/finda#12]
lots of our data is just enumerations of labels.

be able to display only a subset of point by selecting some labels. Deciding on a good interface for this is part of this story.

interface possibility: http://jiren.github.io/filter.js/filterjs-map.html
(filter.js itself is probably too heavy for this project though)

**Comment by ohnorobo** [comment]
different use case, but probably some similar functionality [here](https://github.com/kajic/leaflet-locationfilter/)

**Comment by ohnorobo** [comment]
https://github.com/LuizArmesto/backbone.leaflet

**Comment by paulswartz** [comment]
I have a basic version of this up on my fork: http://paulswartz.github.io/finda/

**Comment by ohnorobo** [comment]
Me gusta.

One thing that comes up poking around is if we want to display this using AND or OR filtering.

It looks like what's currently has going on is AND filtering.
- start out with no facets selected and displaying all data
- when a facet is selected display only the items with that facet
- when more than one facet is selected display only data which meets facet1 AND facet2 AND facet3 ... etc

OR filtering would be something more like http://jiren.github.io/filter.js/filterjs-map.html
- start out with all the fields selected (and have a button to deselect everything)
- when a single facet is selected display only items with that facet
- when multiple facets are selected display items which match facet1 OR facet2 OR facet3 ... etc

There are benefits to both approaches. AND lets you find an individual resources which have a specific mixture of characteristics, OR filtering tends to display more data and allows you to find a group of resources that match a set of needs more quickly.

I'd like to loop Hannah in on this and figure out which would be more useful for her search case, either through email or by asking her to visit a CfB meeting to hash it out.

**Comment by paulswartz** [comment]
Currently, it's actually /more/ confusing; it's AND filtering if the underlying data is a list of options, but OR filtering if it's a single value.  I'd love to have Hannah check it out though, and see what she/they think.

**Comment by paulswartz** [comment]
Oh, and I did have a rationale for the AND/OR, despite the confusion.  I figured that if you were selecting some services, you'd want to see the locations that had all of those services since you needed multiple things.

**Comment by paulswartz** [comment]
![screenshot 2014-02-25 19 39 12](https://f.cloud.github.com/assets/214921/2265289/c4720652-9e7e-11e3-9a25-84bee61757f2.png)

Amazon does it by changing the numbers next to the checkbox to reflect the number of items which will remain when that's clicked.  "Featured Brands" is an OR search; "Features & Apps" is an AND search. I'll try to play with that soon.

**Comment by paulswartz** [comment]
Finally got around to implementing a basic version of the faceting counts: http://paulswartz.github.io/finda/

Known issues:
- clicking on the text doesn't toggle the checkbox
- the filtering of the facets is connected, but checking a Service doesn't update the counts or options of the Categories
- related:, if you filter so far there are no displayed values for a facet, the title is still displayed
- related: if you filter so far there are no options, even the "selected" options disappear

**Comment by paulswartz** [comment]
I think I've addressed those issues; I opened up #55 to merge it in.
