### ISSUE TITLE
landing page

### ISSUE THREAD

**Issue by ohnorobo** [codeforboston/finda#14]
dropping people straight into a map is probably confusing. Instead some sort of directed landing page will help people understand what they're seeing.

I'm partial to http://www.smc-connect.org/ 's landing page. Part of this story is to discuss design choices and options.

**Comment by paulswartz** [comment]
In the short term, something like the Pantry Pickup "about" page could pop up the first time the user visits the page to give some context.

**Comment by WheresHJ** [comment]
Might also want to have something in the config file that lets an admin user put in some custom descriptive text or maybe a custom image.
