### ISSUE TITLE
Filter child care finder by city 

### ISSUE THREAD

**Issue by alexsoble** [codeforboston/finda#145]
Hello Finda friends! 

My team was talking the other day with the folks who run Somerville's Early Childhood hub: http://somervillehub.org/. 

They have lots of info on early childhood care options on their website... **but no map**! They said that they have been dreaming and talking about having a searchable/filterable map for a long, long time.

If we could filter the map view by city, that would be a fantastic step in that direction.

**Comment by drewrwilson** [comment]
:+1:
