### ISSUE TITLE
gh-page hosting doesn't seem to work in fork

### ISSUE THREAD

**Issue by radumas** [codeforboston/finda#147]
According to the wiki, the hosting part should already be handled if I forked the project on github. 

But this would not appear to be the case, since I get a 404 when navigating to http://radumas.github.io/finda

**Comment by paulswartz** [comment]
Hey there!

It looks like your user page at radumas.github.io is interfering with the project page for Finda. You might try looking at the documentation for Github Pages; I'm not sure why they don't work together.

**Comment by radumas** [comment]
Hey Paul,

Close. It seems one has to commit something, anything, to the gh-pages branch in order for github to start hosting that project. Presumably anyone modifying the project with their own data would do that at some point before expecting to see a webmap rather than me, who was skipping some steps just to see what finda looks like when hosted on my own github page.

Thanks,

-Raphael
