### ISSUE TITLE
Rename project to 'Finda', officially

### ISSUE THREAD

**Issue by beechnut** [codeforboston/finda#19]
I genuinely think this platform could be the next Adopta. And while the documentation says **Finda**, the repo is still called `filter-template`.

I'd like to propose that we change the project name & repo name to Finda. I'd like to do a temperature check on this to see what people are thinking. (This is not a poll.) 

Would you please leave a :+1: in the comments if you agree, a :-1: if you do not? Thanks! (Type ':' followed by a +1 or -1 to get the thumb icons.)

**Comment by ohnorobo** [comment]
:+1: I think once this gets to a certain maturity the lgbtq website will break out into its own repo and the more modular/default things will stay here.

**Comment by mjrouser** [comment]
Agreed, Matt.  :+1:

**Comment by ohnorobo** [comment]
Renaming project from filter-template to finda, please stand by...
