### ISSUE TITLE
list view

### ISSUE THREAD

**Issue by paulswartz** [codeforboston/finda#37]
There should be a way to see a list of the items, in addition (or instead, in the case of mobile) to the map view.

**Comment by isaacchansky** [comment]
I'd like to play with this feature, any existing thoughts how we want to do this?

**Comment by ohnorobo** [comment]
Sample implementation here: http://www.pantrypickup.org/

I really like the
select an item on the map <=> select an item on the list
flow

Questions:
- how should this interact with faceting? Should both be allowed
  simultaneously?
- Should we display all the data in the list? The subset visible on the
  map? Something else?
- Should the list be sorted? (proximity?)

**Comment by WheresHJ** [comment]
Paul and I diagrammed this, we have it someplace. I'll look.

Harlan Weber
Designer | Researcher
http://www.hjweber.net

**Comment by ohnorobo** [comment]
https://github.com/isaacchansky/finda/compare/feature;list-view

**Comment by paulswartz** [comment]
This got merged a while back.
