### ISSUE TITLE
Make a "built" version

### ISSUE THREAD

**Issue by calvinmetcalf** [codeforboston/finda#48]
live version via watchify

**Comment by paulswartz** [comment]
[Browserify](http://browserify.org/) is a npm package which bundles all the code into a single file.  It makes loading the page faster since it needs to load fewer files.

**Comment by calvinmetcalf** [comment]
node package

**Comment by beechnut** [comment]
Longer explanation: Deployers who have no intention of developing (out target user) should be able to download a zipped, minified version, add their config, and be done.

We'd browserify to reduce the number of JS files. User-editable CSS and config.json would be the same so folks can still configure.

Smaller size, fewer files, still configurable. :) Finda

**Comment by ohnorobo** [comment]
https://github.com/blog/1547-release-your-software

**Comment by paulswartz** [comment]
Exactly! I think this is going to be what I'm focused on for the week.

**Comment by calvinmetcalf** [comment]
+1 to using browserify with this, and converting the and modules to common
js

**Comment by paulswartz** [comment]
@calvinmetcalf I like the simplicity of Browserify, but is there a way to make the packages such that it the app works without having to go through the build step?

**Comment by calvinmetcalf** [comment]
so you mean having common.js but have it work as separate files and as a bundle? Yes you can use [curl](https://github.com/cujojs/curl) as a module loader which has the ability to do commonjs, though your best bet no matter what the build system is to have the config and the data outside the bundle so that if you need to make changes you only need to change those 2 files so that the only people that need to bother building things are the people mucking about with the interior stuff.

**Comment by paulswartz** [comment]
The workflow that works currently, and that I'd like to have continue to work is:
1. Fork the Finda repo
2. Edit a JS file to add a feature, either through the web interface or locally.
3. Commit that change.
4. Have their change reflected on their Github Pages version.

If there's a way to have that happen with Browserify the way that it currently does with RequireJS, I'd love to know about it.  

I'll checkout Curl more later on, although it seems like it's doing all the same things that RequireJS is currently doing?

**Comment by calvinmetcalf** [comment]
yes, but it has the ability to omit the commonjs wrapper around the files, the other option to look into is https://github.com/jaredhanson/deamdify which allows you to use browserify in amd files
