### ISSUE TITLE
Update config.documentation.md

### ISSUE THREAD

**Issue by paulswartz** [codeforboston/finda#51]
[config.documentation.md](config.documentation.md) is slightly out of date:
- doesn't include `project` or `search` or `geojson_source`
- maxZoom should say what the highest value is (18?)
- properties documentation:
  - should include 'image'
  - should be clearer that having an empty property list in the config displays the property value as plain text
  - (maybe) clarify that the properties get an ID with their name, for styling

**Comment by ohnorobo** [comment]
All the stuff on config.documentation.md should be moved to its own wiki page. The file in the repo should be removed.

**Comment by ohnorobo** [comment]
https://github.com/codeforboston/finda/wiki/Configuration

**Comment by paulswartz** [comment]
This should still get done, just as a part of the above Wiki page instead of in the repo.

**Comment by ohnorobo** [comment]
Added more documentation. I wasn't sure about images in properties, or how to succinctly explain faceting.
