### ISSUE TITLE
[discuss] refactor CSS so it's clear what's "needed" and what's user-configurable

### ISSUE THREAD

**Issue by paulswartz** [codeforboston/finda#57]
Right now, there are parts of [style.css](https://github.com/codeforboston/finda/blob/gh-pages/styles/style.css) which configure things for the user (the #phone_number/#address/#organization_name lines) and the rest which set up the default styles for Finda.  For clarity, maybe this should be refactored, either:
- moving the Finda-defaults into a file we `@import` from `style.css`, or
- moving the user-customized styles into a `local.css` (or similar) which we include from `style.css`.

**Comment by davidlago** [comment]
Modified config page in wiki to point to the new properties.css file for info box styling.

**Comment by paulswartz** [comment]
Closed by #64.
