### ISSUE TITLE
logo

### ISSUE THREAD

**Issue by paulswartz** [codeforboston/finda#70]
All good projects have a logo.

**Comment by ohnorobo** [comment]
magnifying glass over a map?

**Comment by WheresHJ** [comment]
I had an idea. Have some others too, but just sketched this out.

![finda_logo_idea1](https://f.cloud.github.com/assets/642810/2348976/75680228-a55e-11e3-9b90-f2c249980fa8.png)

**Comment by beechnut** [comment]
@WheresHJ: Pretty! It references how the data is in the cloud and the paper map is accessible for our non-tech audience.

I was thinking maybe the word "Finda" with a map marker as the "i", but after looking at Harlan's logo that feels like a step backward.

**Comment by WheresHJ** [comment]
I tried to blend it a bit, but I'll let you guys judge. I tried the standard map marker, but then it started looking like "Fonda", so I switched to a pin and it was better.

![finda_logo_idea1a](https://f.cloud.github.com/assets/642810/2350768/95ea34ce-a574-11e3-9b3b-899393a67070.png)
![finda_logo_idea1b](https://f.cloud.github.com/assets/642810/2350769/95ea5800-a574-11e3-95ce-74641ceba303.png)

**Comment by paulswartz** [comment]
I like the pin, but it looks a little weird since it's so much thinner than the rest of the text.  Maybe a lighter weight font, or a heavier pin?

**Comment by paulswartz** [comment]
We went without the pin for now.
