### ISSUE TITLE
hook up (Google?) analytics

### ISSUE THREAD

**Issue by paulswartz** [codeforboston/finda#77]
It would be nice to track who's using Finda, what browser/OS they're using, and what they do with the app (do they search for addresses? Do they filter? How many features do they look at.

We should hook up some kind of analytics so that we can get some of this data, at least by default. Probably it should be configurable, so privacy-conscious groups can disable it.

**Comment by davidlago** [comment]
Does Code for Boston have a Google Analytics account? If not, I can create one and add the hooks to finda's index.

**Comment by ohnorobo** [comment]
If we have one @WheresHJ would know.

**Comment by WheresHJ** [comment]
We do. Let's hook it up on Tuesday - and we definitely need to put in a way
out.

On Sunday, March 9, 2014, Sarah Laplante notifications@github.com wrote:

> If we have one @WheresHJ https://github.com/WheresHJ would know.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/codeforboston/finda/issues/77#issuecomment-37145465
> .

## 

Sent from Gmail Mobile

**Comment by ohnorobo** [comment]
One thing to keep in mind. This is eventually going to be split into two repos. The 'upstream' repository that people fork to start their own websites (which will keep thus url), and a dedicated site for the lgbtq data. We definitely don't want to have our personal google analytics set up in the first one.
That might be a long way off though, and it's a pretty easy thing to remove when the time comes.

**Comment by paulswartz** [comment]
@beechnut says that we can use multiple Google tokens.  By default, we should use both a user-specified token and the @codeforboston token, so that we can see who's using Finda.

**Comment by beechnut** [comment]
There could be a field in config.json like `private: false`, if set to `true` would not include our Google Analytics snippet.
