### ISSUE TITLE
when hovering over a feature, should show the name

### ISSUE THREAD

**Issue by paulswartz** [codeforboston/finda#83]
Might need to add a config element for which property is the name.

**Comment by isaacchansky** [comment]
Thought I'd jump in on this issue as a way to get familiar with the codebase :) 
Any existing ideas of how best to show the name (i.e tooltip or something right next to the cursor)?

**Comment by paulswartz** [comment]
I think that Leaflet has something for this: http://leafletjs.com/reference.html.  You should be able to attach it with the setupFeature function; that's defined in src/map.js.

**Comment by ohnorobo** [comment]
marker tooltips: http://leafletjs.com/reference.html#marker-title

**Comment by isaacchansky** [comment]
Thanks for pointing me in the right direction @paulswartz & @ohnorobo . I added a new config property of "preview_attribute" to specify the property you want as display text. 

https://github.com/isaacchansky/finda/commit/c1cef139bf91246f2a92ddc4523579624e3dee64

![screen shot 2014-03-13 at 10 37 38 pm](https://f.cloud.github.com/assets/1397914/2417517/b159f10a-ab22-11e3-852c-6250fa2d8810.png)

There's some weird flickering when you hover near the top of the feature/marker that I haven't looked into yet. Also should probably cancel hover event on features that are selected.

**Comment by ohnorobo** [comment]
One nice thing about this project it that it automatically throws up a website when you fork it. So if you want to show people your work (on your gh-pages branch) you can just link to http://isaacchansky.github.io/finda/

**Comment by isaacchansky** [comment]
Thanks @ohnorobo , kind of missed the core concept there didn't I... >.< 
Will do from now on!

**Comment by isaacchansky** [comment]
This is done in PR #89 . But, there is a bug introduced where if you _close_ an info box, the tooltip doesn't rebind to the 'new' icon when in changes from gray -> blue so it defaults to sit directly _over_ the icon. I've opened issue #94 for this.

**Comment by isaacchansky** [comment]
Pretty sure this is solved... cool to close this issue?
